name: Publish Release
on:
  workflow_dispatch:
    inputs:
      DOWNLOAD_URL:
        description: 'DOWNLOAD_URL'
        required: true
        default: 'https://download857.mediafire.com/qc56ccd1dq5gIKEt1HKGO3OBnNPRkXQm1KU8mpLJyD3OIyVND-kLYq7VyCPHj-PYN2zUOGS_fUlEzr6rzR4dZa84Pbskb6mgZD2_IwyTddU8EylMVHsdAjsT_Gh4NzZdfA3kMzci6EzV89EQRJnVUsb8h0lWHT4PFHvzKp86IZDdyw/mosmnmibs02fz22/X657C-H6117G-RGo-INJO-LC-211214V384%28MobiFirmware.com%29.zip'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'INFINIX SMART 5 X657C'
      ROM_TYPE:
        description: 'ROM_TYPE'
        required: true
        default: 'STOCK ROM'
      FILES_TYPE:
        description: 'FILES_TYPE'
        required: true
        default: 'ALL ROM FILES'
      DIR_NAME:
        description: 'DIR_NAME'
        required: true
        default: 'rom'
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v3

    - name: Prepare the environment
      run: |
        sudo apt install git aria2 wget tar simg2img -y
    
    - name: Checkout repository
      uses: actions/checkout@v2

      # Add a step to download the archive that contains the files you want to publish
    - name: Download Archive
      run: |
           # Replace the URL with the actual URL of the archive you want to download
           wget -O archive.zip  ${{ github.event.inputs.DOWNLOAD_URL }}
           mkdir ${{ github.event.inputs.DIR_NAME }}
           unzip archive.zip -d ${{ github.event.inputs.DIR_NAME }}/*
          
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ github.event.inputs.DOWNLOAD_URL }}/*
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ github.event.inputs.FILES_TYPE }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: ${{ github.event.inputs.ROM_TYPE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
