name: Extract and upload compressed archive

on:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download compressed archive
        run: curl -L https://github.com/bard/bard/archive/refs/heads/main.zip -o barda.zip

      - name: Extract compressed archive
        run: unzip barda.zip

  upload:
    runs-on: ubuntu-latest

    needs: extract

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git upload-release-asset

      - name: Upload all decompressed files to releases page
        run: |
          for file in $(find . -type f); do
            upload-release-asset \
              repo_token=${{ secrets.GITHUB_TOKEN }} \
              tag=${{ github.ref }} \
              asset_name=${file} \
              file=${file}
          done
